package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class missingperson_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<!--\r\n");
      out.write("Design by Free CSS Templates\r\n");
      out.write("http://www.freecsstemplates.org\r\n");
      out.write("Released for free under a Creative Commons Attribution 2.5 License\r\n");
      out.write("-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function doMiss()\r\n");
      out.write("{\r\n");
      out.write(" var a=document.getElementById(\"fir\");\r\n");
      out.write("  var b=document.getElementById(\"dis\");\r\n");
      out.write("  var c=document.getElementById(\"pol\");\r\n");
      out.write("  var d=document.getElementById(\"datem\");\r\n");
      out.write("  var e=document.getElementById(\"dater\");\r\n");
      out.write("   var f=document.getElementById(\"sex\");\r\n");
      out.write("   var n=document.getElementById(\"age\");\r\n");
      out.write("  var g=document.getElementById(\"complex\");\r\n");
      out.write("  var h=document.getElementById(\"ht\");\r\n");
      out.write("  var i=document.getElementById(\"fat\");\r\n");
      out.write("  var j=document.getElementById(\"idm\");\r\n");
      out.write("  \r\n");
      out.write("   var k=document.getElementById(\"app\");\r\n");
      out.write("  var l=document.getElementById(\"nam\");\r\n");
      out.write("  var m=document.getElementById(\"brief\");\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  if(a.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the fir no\");\r\n");
      out.write("\ta.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("  \r\n");
      out.write("   if(b.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the district\");\r\n");
      out.write("\tb.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t if(c.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the police station\");\r\n");
      out.write("\tc.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("   if(d.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the date of missing\");\r\n");
      out.write("\td.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t if(e.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the date of reporting\");\r\n");
      out.write("\te.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t if(f.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the sex \");\r\n");
      out.write("\tf.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t if(n.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter age\");\r\n");
      out.write("  n.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("   if(g.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the complexion\");\r\n");
      out.write("\tg.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t if(h.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the height\");\r\n");
      out.write("\th.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("   if(i.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter whether fat,plump or lean\");\r\n");
      out.write("\ti.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t if(j.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the identification marks\");\r\n");
      out.write("\tj.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\t if(k.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the deatails of wearing apparels\");\r\n");
      out.write("\tk.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("   if(l.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the name and address of missing person\");\r\n");
      out.write("\tl.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t if(m.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the brief of the case\");\r\n");
      out.write("\tm.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("\tcolor: #CC9999;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".style11 {\r\n");
      out.write("\tcolor: #999999;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".style13 {color: #CC0033; font-weight: bold; }\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t\t<h1>CrimeStation</h1>\r\n");
      out.write("\t\t<h2>within the hands of safe </h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"adminhome.html\">Adminhome </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"viewusercomplaint.jsp\">Usercomplaint </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"viewusercrime.jsp\">Usercrime</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"viewcontacts.jsp\">Contacts</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"login.jsp\">Logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("  <div id=\"colOne\">\r\n");
      out.write("    <form id=\"form1\" name=\"form1\" method=\"post\" action=\"missingpersonaction.jsp\">\r\n");
      out.write("<table width=\"411\" border=\"0\" align=\"center\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"49\" colspan=\"2\"><div align=\"center\" class=\"style11\">MISSING PERSONS </div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"191\" height=\"52\"><div align=\"right\" class=\"style13\">FIR No: </div></td>\r\n");
      out.write("    <td width=\"204\">\r\n");
      out.write("      <label>\r\n");
      out.write("        <input name=\"fir\" type=\"text\" id=\"fir\" />\r\n");
      out.write("        </label>    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"53\"><div align=\"right\" class=\"style13\">District:</div></td>\r\n");
      out.write("    <td><input name=\"dis\" type=\"text\" id=\"dis\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"51\"><div align=\"right\" class=\"style13\">Place: </div></td>\r\n");
      out.write("    <td><input name=\"pol\" type=\"text\" id=\"pol\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"52\"><div align=\"right\" class=\"style13\">Date of missing: </div></td>\r\n");
      out.write("    <td><input name=\"datem\" type=\"text\" id=\"datem\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"54\"><div align=\"right\" class=\"style13\">Date of report: </div></td>\r\n");
      out.write("    <td><input name=\"dater\" type=\"text\" id=\"dater\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"55\"><div align=\"right\" class=\"style13\">Sex </div></td>\r\n");
      out.write("    <td><input name=\"sex\" type=\"text\" id=\"sex\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"55\"><div align=\"right\" class=\"style13\">Age</div></td>\r\n");
      out.write("    <td><input name=\"age\" type=\"text\" id=\"age\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"51\"><div align=\"right\" class=\"style13\">Complexion:</div></td>\r\n");
      out.write("    <td><input name=\"complex\" type=\"text\" id=\"complex\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"54\"><div align=\"right\" class=\"style13\">Height:</div></td>\r\n");
      out.write("    <td><input name=\"ht\" type=\"text\" id=\"ht\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"51\"><div align=\"right\" class=\"style13\">Whether fat,plump or lean: </div></td>\r\n");
      out.write("    <td><input name=\"fat\" type=\"text\" id=\"fat\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"51\"><div align=\"right\" class=\"style13\">Identification marks: </div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <label>\r\n");
      out.write("        <textarea name=\"idm\" id=\"idm\"></textarea>\r\n");
      out.write("        </label>    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"84\"><div align=\"right\" class=\"style13\">Details of wearing apparels including ornaments at the time of missing: </div></td>\r\n");
      out.write("    <td><textarea name=\"app\" id=\"app\"></textarea></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"74\"><div align=\"right\" class=\"style13\">Name and address of missing person: </div></td>\r\n");
      out.write("    <td><textarea name=\"nam\" id=\"nam\"></textarea></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"52\"><div align=\"right\" class=\"style13\">Brief of the case: </div></td>\r\n");
      out.write("    <td><textarea name=\"brief\" id=\"brief\"></textarea></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"52\" colspan=\"2\">\r\n");
      out.write("      <label></label>\r\n");
      out.write("      \r\n");
      out.write("        <div align=\"center\">\r\n");
      out.write("          <input type=\"submit\" name=\"Submit2\" value=\"Submit\" onclick=\"return doMiss()\" /> \r\n");
      out.write("          <input type=\"reset\" name=\"Reset\" value=\"Reset\" />\r\n");
      out.write("          </div>\r\n");
      out.write("      <div align=\"center\"></div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"52\" colspan=\"2\">\r\n");
      out.write("      <label>\r\n");
      out.write("      <div align=\"center\"></div>\r\n");
      out.write("      <div align=\"center\"><a href=\"LargeUpload.jsp\">click here to upload photo</a>      \r\n");
      out.write("          </label>  \r\n");
      out.write("      </div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("    <div>\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t<div id=\"colTwo\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <div align=\"center\"><strong> \r\n");
      out.write("\t\t\t    </strong>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<h2>New Additions</h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"newadmin.jsp\">New admin </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"hotnews.jsp\">Hot News </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"viewhotnews.jsp\">View Hot News </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"viewfeedback.jsp\">View Feedback </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mostwanted.jsp\">Most Wanted </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"viewadminwanted.jsp\">View/Delete MostWanted </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"missingperson.jsp\">Missing Persons </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"viewadminmissing.jsp\">View/Delete Missing Persons </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"criminalregister.jsp\">Criminal Register </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"viewcomplaintreply.jsp\">View Allcomplaintreply </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"prisonerreg.jsp\">Prisoners Register </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"prisonerreport.jsp\">ViewPrisonerReport </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"history.jsp\">History</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"viewhistory.jsp\">View History</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"fir.jsp\">FIR</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"firreport.jsp\">FIR Report</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<h2>Account Settings </h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminchangepass.jsp\">Change Password </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"criminalreport.jsp\">All CriminalReport </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<h2>More Facilities </h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"chatlogin.jsp\">Chat</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"compose.jsp\">Mail</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t<p>Copyright &copy; 2009 cfm. Designed by<em class=\"style1\"> <a href=\"http://www.freecsstemplates.org/\">www.crimefilemanagement.com</a></em></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
