package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<!--\r\n");
      out.write("Design by Free CSS Templates\r\n");
      out.write("http://www.freecsstemplates.org\r\n");
      out.write("Released for free under a Creative Commons Attribution 2.5 License\r\n");
      out.write("-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function doCheck()\r\n");
      out.write("{\r\n");
      out.write("  var a=document.getElementById(\"username\");\r\n");
      out.write("  var b=document.getElementById(\"password\");\r\n");
      out.write("  var c=document.getElementById(\"conpass\");\r\n");
      out.write("  var d=document.getElementById(\"name\");\r\n");
      out.write("  var e=document.getElementById(\"desig\");\r\n");
      out.write("  var f=document.getElementById(\"offadd\");\r\n");
      out.write("  var g=document.getElementById(\"phno\");\r\n");
      out.write("  var h=document.getElementById(\"address\");\r\n");
      out.write("  var i=document.getElementById(\"pincode\");\r\n");
      out.write(" var j=document.getElementById(\"phoneno\");\r\n");
      out.write("  var k=document.getElementById(\"email\");\r\n");
      out.write("\r\n");
      out.write("  if(a.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the username\");\r\n");
      out.write("\ta.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("  \r\n");
      out.write("    if(b.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the password\");\r\n");
      out.write("\tb.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\telse if((b.value.length)<6)   \r\n");
      out.write("\t{\r\n");
      out.write("\t alert(\"password should contain atleast 6 characters \");\r\n");
      out.write("\t b.focus();\r\n");
      out.write(" return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t\r\n");
      out.write("  if(c.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the confirm password\");\r\n");
      out.write("\tc.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t   if((c.value)!=(b.value))\r\n");
      out.write("\t\t   {\r\n");
      out.write("\t\t   alert(\"Re-enter the password\");\r\n");
      out.write("\t\t   c.focus();\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  if(d.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the name\");\r\n");
      out.write("    d.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t if(e.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the designation\");\r\n");
      out.write("\te.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t  if(f.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the official address\");\r\n");
      out.write("\tf.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("  \r\n");
      out.write("    if(g.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the phone no:\");\r\n");
      out.write("    g.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t  if(h.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the address\");\r\n");
      out.write("\th.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  if(i.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the pincode\");\r\n");
      out.write("\ti.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t else if(!parseInt(i.value))\r\n");
      out.write("\t\t{    \r\n");
      out.write("                    alert(\"Enter Integer\");\r\n");
      out.write("\t\t    return false;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("              else if(((i.value.length)>6))\r\n");
      out.write("\t        {\r\n");
      out.write("\t               alert(\"Pin no: should contain 6 integers \");  \t            \r\n");
      out.write("\t               i.focus();\r\n");
      out.write("\t               return false;\r\n");
      out.write("                 }\r\n");
      out.write("\t\r\n");
      out.write("  if(j.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the phone number\");\r\n");
      out.write("\tj.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("   else if(!parseInt(j.value))\r\n");
      out.write("\t\t{    \r\n");
      out.write("                    alert(\"Enter valid Phone number \");\r\n");
      out.write("\t\t    return false;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("            else if(((j.value.length)<6) || ((j.value.length)>11))\r\n");
      out.write("\t                     {\r\n");
      out.write("\t               alert(\"Phone no should contain atleast 6 integers \");  \r\n");
      out.write("\t            \r\n");
      out.write("\t               j.focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("\t                  }                 \r\n");
      out.write("  \r\n");
      out.write("    if(k.value == \"\")\r\n");
      out.write("  {\r\n");
      out.write("    alert (\"enter the email\");\r\n");
      out.write("\tk.focus();\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t else if(k.value.indexOf('@')==-1)\r\n");
      out.write("\t\t      {\r\n");
      out.write("\t\t       alert(\"Use @ email correctly\");\r\n");
      out.write("\t\t       k.focus();\r\n");
      out.write("\t\t       return false;\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\r\n");
      out.write("\t  else if(k.value.indexOf('.')==-1)\r\n");
      out.write("\t\t       {\r\n");
      out.write("\t\t        alert(\"Use . email correctly\");\r\n");
      out.write("\t\t        k.focus();\r\n");
      out.write("\t\t        return false;\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("\tcolor: #CC9999;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".style4 {\r\n");
      out.write("\tcolor: #C14744;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".style8 {color: #CCCC99}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t\t<h1>CrimeStation</h1>\r\n");
      out.write("\t\t<h2>within the hands of safe </h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"adminhome.html\">my home </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"latestnews.jsp\">latest news </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"feedback.jsp\">feedbacks</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"login.jsp\">logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("  <div id=\"colOne\">\r\n");
      out.write("    <p>&nbsp;</p>\r\n");
      out.write("    <div><form name=\"form1\"method=\"get\" action=\"newadminaction.jsp\" >\r\n");
      out.write("\t\t  <table width=\"455\" border=\"0\" align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write(" <td height=\"34\" colspan=\"2\"><div align=\"center\" class=\"style1 style8\">ADMIN REGISTRATION </div></td>\r\n");
      out.write(" </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  \r\n");
      out.write("    <td height=\"31\" scope=\"col\"><div align=\"right\" class=\"style4\">Username:</div></td>\r\n");
      out.write("    <th width=\"238\" scope=\"col\">\r\n");
      out.write("      <div align=\"left\">\r\n");
      out.write("        <input name=\"username\" type=\"text\" id=\"username\" />\r\n");
      out.write("        </div>      </th>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Password</span>:</div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <input name=\"password\" type=\"password\" id=\"password\" maxlength=\"8\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Confirm password</span>:</div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <input name=\"conpass\" type=\"password\" id=\"conpass\" maxlength=\"8\" />      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td scope=\"row\"><div align=\"right\"><span class=\"style4\">Secret question</span>: </div></td>\r\n");
      out.write("    <td><label>\r\n");
      out.write("      <select name=\"select\">\r\n");
      out.write("        <option>what is your pet's name?</option>\r\n");
      out.write("        <option>where is your house?</option>\r\n");
      out.write("        <option>what is the name of your first school?</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </label></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"29\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Answer</span>:</div></td>\r\n");
      out.write("    <td><label>\r\n");
      out.write("      <input name=\"ans\" type=\"text\" id=\"ans\" />\r\n");
      out.write("    </label></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"28\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Name</span>:</div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <input name=\"name\" type=\"text\" id=\"name\" />      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Designation</span>:</div></td>\r\n");
      out.write("    <td><input name=\"desig\" type=\"text\" id=\"desig\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"44\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Official address</span>: </div></td>\r\n");
      out.write("    <td><textarea name=\"offadd\" id=\"offadd\"></textarea></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Phone no</span>: </div></td>\r\n");
      out.write("    <td><input name=\"phno\" type=\"text\" id=\"phno\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td scope=\"row\"><div align=\"right\"> <span class=\"style4\">Residential address</span>:</div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <textarea name=\"address\" id=\"address\"></textarea>      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"31\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Pincode</span>:</div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <input name=\"pincode\" type=\"text\" id=\"pincode\" />      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"29\" scope=\"row\"><div align=\"right\"><span class=\"style4\">Phoneno</span>:</div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <input name=\"phoneno\" type=\"text\" id=\"phoneno\" />      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td scope=\"row\"><div align=\"right\"><span class=\"style4\">E-Mail</span>:</div></td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <input name=\"email\" type=\"text\" id=\"email\" />      </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th scope=\"row\">&nbsp;</th>\r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th colspan=\"2\" scope=\"row\">\r\n");
      out.write("      <input name=\"Submit\" type=\"Submit\" id=\"submit\" value=\"Register\" onclick=\"return doCheck()\" />&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t  \r\n");
      out.write("      <input name=\"reset\" type=\"reset\" id=\"cancel\" value=\"Reset\" />      </th>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t<div id=\"colTwo\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t  <div align=\"center\"><strong> \r\n");
      out.write("\t\t\t    </strong>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t\t  <form method=\"get\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"text\" id=\"textfield1\" name=\"textfield1\" value=\"\" size=\"18\" />\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"submit\" id=\"submit1\" name=\"submit1\" value=\"Search\" />\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t  </form>\r\n");
      out.write("\t\t  </li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<h2>New Additions</h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"newadmin.jsp\">New admin </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"hotnews.jsp\">Hot News </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mostwanted.jsp\">Most Wanted </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"missingperson.jsp\">Missing Persons </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"criminalregister.jsp\">Criminal Register </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"postmortum.jsp\">Post Mortum </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"prisonerreg.jsp\">Prisoners Register </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"history.jsp\">History</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"fir.jsp\">FIR</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"chargesheet.jsp\">Chargesheet</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<h2>Account Settings </h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"adminchangepass.jsp\">Change Password </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<h2>More Facilities </h2>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"chatlogin.jsp\">Chat</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"compose.jsp\">Mail</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t<p>Copyright &copy; 2009 cfm. Designed by<em> <span class=\"style1\"><a href=\"http://www.freecsstemplates.org/\">www.crimefilemanagement.com</a></span></em></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
